[package]
name = "iris-lsm"
version = "0.1.0"
edition = "2024"
repository = "https://github.com/azusachino/iris-lsm"

[dependencies]
anyhow = "1"
thiserror = "2"

tokio = { version = "1", features = ["full"] }

tracing = "0.1"
tracing-subscriber = "0.3"
